### ISSUE TITLE
Always show "Incomplete config, missing key:".

### ISSUE THREAD

**Issue by E-Zuo** [jangxx/twitch-auto-recorder-3000#3]
When I try to input clientid, twitch-secret, username, it always show **Incomplete config, missing key:**
like:

```
(venv) D:\twitch_auto_recorder_3000_3_7_16\twitch-auto-recorder-3000>python main.py --twitch-clientid <my_twitch_clientid>
Incomplete config, missing key: twitch.secret

(venv) D:\twitch_auto_recorder_3000_3_7_16\twitch-auto-recorder-3000>python main.py --twitch-secret <my_twitch_secret>
Incomplete config, missing key: twitch.clientid

(venv) D:\twitch_auto_recorder_3000_3_7_16\twitch-auto-recorder-3000>python main.py -s <username>
Incomplete config, missing key: twitch.clientid
```

Should I input them by myself?

**Comment by jangxx** [comment]
I'm not sure what the issue is, everything seems to work as it should?

You need to give it all required parameters at the same time, so the minimal command looks like this:

    $ python main.py --twitch-clientid <my_twitch_clientid> --twitch-secret <my_twitch_secret> -s <username>

In your examples you only gave it one of the parameters, so it obviously complains about the others missing.

**Comment by E-Zuo** [comment]
Okay I try it, it work, thank you!
