### ISSUE TITLE
quality defaults to last configured

### ISSUE THREAD

**Issue by stahr** [jangxx/twitch-auto-recorder-3000#5]
in the main loop in main.py, quality is not ever set before startRcording is invoked, so it defaults to the quality of the last username:quality configured.  The solution is to assign it before Recorder is setup and invoked:

                    if is_live and username not in recorders:
                        quality = watches[username]["quality"]
                        recorders[username] = Recorder(username, quality, config.value("output_path"), config.value("streamlink_options"), plugins)
                        recorders[username].startRecording(streams[username])

**Comment by jangxx** [comment]
Oh shit, you're absolutely right. Let me fix that real quick.

**Comment by jangxx** [comment]
Fixed in da26bd2b6e318136e32f877473dc11b44245c0c4
