### ISSUE TITLE
Could not find quality 'best' in the list of available qualities. Options are:

### ISSUE THREAD

**Issue by bolbies** [jangxx/twitch-auto-recorder-3000#6]
Hi, similar to #4, I keep getting the following error:
`Could not find quality 'best' in the list of available qualities. Options are:`

There is nothing else after "Options are:", it's just blank. I use the config file and have not told the tool to record in a specific quality, so it uses the default recording quality.

Any Idea of what's wrong and how I can fix it?

**Comment by bolbies** [comment]
It seems that Twitch updated stuff on their end to disable 3rd party functionality, including Streamlink and adblockers, so it seems like this issue is a streamlink problem. Hopefully they can fix it soon

**Comment by jangxx** [comment]
I don't know if you saw it already, but _right now_ the recording seems to work again. I doubt this is going to be permanent, but for the time being it does.

**Comment by bolbies** [comment]
Yeah it looks like they rolled back for the time being
