### ISSUE TITLE
Filenames aren't readable via smb share

### ISSUE THREAD

**Issue by MisterSizzles** [jangxx/twitch-auto-recorder-3000#9]
![w_GQq](https://github.com/jangxx/twitch-auto-recorder-3000/assets/17134137/b0b26638-e4c5-48c7-95d3-450d9004ef69)

Files contain the normal stream title in the Linux environment, but aren't readable when shared on samba to windows. Is there something that can be altered in the config file to change this? Thank you.

**Comment by jangxx** [comment]
Right now there is no way to change the filename generation with a config option. It is something I could add though and might also come in handy for other use cases.

For your particular SMB problem, I can also suggest using [vfs_catia](https://www.samba.org/samba/docs/current/man-html/vfs_catia.8.html), which allows you to map illegal characters in samba to different ones, that look similar but don't trip up Window's weird filename restrictions.

Personally I use this config in my smb.conf:

```ini
# this all goes into the [global] section
mangled names = no
catia:mappings = 0x22:0x201f,0x2a:0x2217,0x2f:0x2215,0x3a:0x2236,0x3c:0x2039,0x3e:0x203a,0x3f:0xbf,0x5c:0x2216,0x7c:0x2223
vfs objects = catia
```

it maps symbols like `"` to `‟` and `*` to `∗` for example. Works pretty well for my own use case but it would still be cool to have a configurable template system for filenames as well. If I find the time I can look into adding that as a feature.

**Comment by MisterSizzles** [comment]
> Right now there is no way to change the filename generation with a config option. It is something I could add though and might also come in handy for other use cases.
> 
> For your particular SMB problem, I can also suggest using [vfs_catia](https://www.samba.org/samba/docs/current/man-html/vfs_catia.8.html), which allows you to map illegal characters in samba to different ones, that look similar but don't trip up Window's weird filename restrictions.
> 
> Personally I use this config in my smb.conf:
> 
> ```ini
> # this all goes into the [global] section
> mangled names = no
> catia:mappings = 0x22:0x201f,0x2a:0x2217,0x2f:0x2215,0x3a:0x2236,0x3c:0x2039,0x3e:0x203a,0x3f:0xbf,0x5c:0x2216,0x7c:0x2223
> vfs objects = catia
> ```
> 
> it maps symbols like `"` to `‟` and `*` to `∗` for example. Works pretty well for my own use case but it would still be cool to have a configurable template system for filenames as well. If I find the time I can look into adding that as a feature.

Adding this to the config is exactly what I needed, all the proper titles are there now. Thanks.

![Capture](https://github.com/jangxx/twitch-auto-recorder-3000/assets/17134137/d05ac5bf-2a40-4162-81d7-df451882a7c5)
